### ISSUE TITLE
全、半形符號問題

### ISSUE THREAD

**Issue by shiami** [i3thuan5/rime_taigi_poj_hanlo#1]
漢羅輸入法基本是用羅馬字半形字，所pái nā Rime輸入法方案（schema）ê選項，預設是半形。
> switches:
>   - name: full_shape
>     states: [ 半形, 全形 ]
>     reset: 0

符號表有hun全形（full_shape）kap 半形（half_shape），
m̄-koh phah漢羅ê時陣，符號表應該ài用全形。
Nā照使用koàn-sì，無可能切來切去。
To̍h ài用半形ê符號表強制輸出全形符號。
> punctuator:
>   full_shape:
>     ',' : { commit: ， }
>     '.' : { commit: 。 }
>     '?' : { commit: ？ }
> 
>   half_shape:
>     ',' : [ "，", "," ]
>     '.' : [ "。", "." ]
>     '?' : { commit: '？' }

M̄-koh tī `punctuator` 內底，
直接用 `commit` ē-sái輸出全形，
用 `[ ... ]` 選項soah ē hō͘ 強制轉做半形ê字。
頂koân ê例，
「，」kap 「。」ē轉做半形「,」kap「.」，
「？」to̍h ē是全形。

變做kan-na ē-sái強制設1-ê全形ê符號來用。

Ài koh看kám有hoat-tō͘修改--無。

**Comment by shiami** [comment]
應該ē-sái用 `ascii_punct` （漢字、拉丁文標點轉換開關切換）完成。

M̄-koh使用者可能ē無siáⁿ清楚，nā限定phah漢羅
，to̍h強制設定做半形文字、漢字標點符號。

例：

>   - name: full_shape
>     states: [ 半形, 全形 ]
>     reset: 0    # 0 是半形
>   - name: ascii_punct
>     states: [ 。，, ．， ]
>     reset: 0    # 0 是漢字標點符號

**Comment by sih4sing5hong5** [comment]
到時應該關掉全半形功能，全部指定好半形羅馬字、全形標點就好

**Comment by sih4sing5hong5** [comment]
我是感覺`rime_api_console` 創起來，加入來 `BDD`，才改全半形 ê schema較好

**Comment by shiami** [comment]
Hó

**Comment by shiami** [comment]
Thàu-kòe siu-kái su-ji̍p-hoat hong-àn siat-tēng kái-koat.

https://github.com/i3thuan5/rime_taigi_poj_hanlo/blob/master/taigi_pojhanlo_sujiphoat/taigi_pojhanlo.schema.yaml

```
switches:
  - name: ascii_mode
    states: ["台文", "英文"]
    reset: 0   # 預設0是台文，1是英文
  - name: full_shape
    states: ["半形羅馬字","全形羅馬字"]
    reset: 0    # 0是半形，1是全形
  - name: ascii_punct
#    states: ["全形羅馬字符號", "半形羅馬字符號"] 
    reset: 1    # 0爲全形符號，1爲半形符號。
```

1. full_shape 預設設定tī半形
2. ascii_punct 無顯示選項
3. 符號表ê半形kap全形lóng設kāng款
https://github.com/i3thuan5/rime_taigi_poj_hanlo/blob/master/taigi_pojhanlo_sujiphoat/taigi_pojhanlo.symbol.yaml
